# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='price',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
