# Generated by Django 2.0 on 2018-01-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0002_flower_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='in_cart',
            field=models.BooleanField(default=False),
        ),
    ]
